### ISSUE TITLE
혹시 vuetify로 제작한 버전은 없나요?

### ISSUE THREAD

**Issue by siz0001** [iamport/iamport-vue-example#5]
이거 쓰려면 ant-design-vue 라고 하는 ui framework를 따로 또 깔아야해서..
일반적으로 vue로 개발하면 가장 많이 쓰는게 vuetify 인데 vuetify 버전이 있으면 훨씬 더 많은 사람들이 사용할 것 같습니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

이미 아시겠지만, 아임포트 결제 모듈을 자체를 붙이기 위해서 ant-design-vue 든 vuetify든 그 어떤 UI framework를 사용하실 필요가 없습니다.
이해를 돕기 위해 여러가지 PG사와 결제수단으로 결제를 해보실 수 있도록 UI를 작성하는 과정에서 사용했을 뿐이라
결제 연동하는 로직에서 고객님들께서 사용하시는 UI framework의 종류에 따라 달라지는 것이 거의 없으니 참고 부탁드립니다.

참고 부탁드립니다.
감사합니다.

**Comment by siz0001** [comment]
안녕하세요,
제가 코딩 초보라 그런데 vuetify 예제 하나 만들어주시면 더 빠르게 적용이 가능할것 같아 문의드립니다
 혹시 가능할까요? ㅠㅠ
​
-----Original Message-----

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

앞서 말씀드린대로, 결제 모듈 연동하실때는 vuetify가 필요없으시고, 아래와 같이 해주시면 됩니다.

1. 최상위 index.html 파일에 [jQuery](https://github.com/iamport/iamport-vue-example/blob/master/public/index.html#L11)와 [아임포트 javascript SDK](https://github.com/iamport/iamport-vue-example/blob/master/public/index.html#L13)를 추가한다:
2. 결제 페이지에서 결제 버튼을 [눌렀을때](https://github.com/iamport/iamport-vue-example/blob/master/src/views/Payment.vue#L168) 가맹점을 식별할 수 있도록 [IMP.init 함수를 호출](https://github.com/iamport/iamport-vue-example/blob/master/src/views/Payment.vue#L189)하고 결제창을 렌더링하기 위해 [IMP.request_pay 함수를 호출](https://github.com/iamport/iamport-vue-example/blob/master/src/views/Payment.vue#L216)한다.

`IMP.init` 함수를 호출하실때는 첫번째 파라메터로 [아임포트 관리자페이지](https://admin.iamport.kr) > 시스템설정 > 내정보에 정의되어있는 `가맹점 식별코드`를 넣어주시면 됩니다.

```
IMP.init('여기에_가맹점_식별코드를_넣어주세요');
```

`IMP.request_pay` 함수를 호출하실때는 첫번째 파라메터로 [결제에 필요한 데이터](https://github.com/iamport/iamport-vue-example/blob/master/src/views/Payment.vue#L190)를, 두번째 파라메터로 [결제 프로세스 완료 후 실행될 함수](https://github.com/iamport/iamport-vue-example/blob/master/src/views/Payment.vue#L249)를 넣어주시면 됩니다.

위 모든 로직은 vuetify와는 별개로 순전히 javascript 코드이기 때문에 위 과정대로 하시면 무리없이 진행 가능하실 것 같습니다.
이용에 참고 부탁드립니다.
감사합니다.
